<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.9" />
	</ItemGroup>

	<PropertyGroup>
		<BuildDate>$([System.DateTime]::UtcNow.ToString("yyyy.MM.dd HH:mm:ss"))</BuildDate>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyMetadata Include="BuildDate" Value="$(BuildDate)" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\EverModern.Blazor.DirectCommunication\EverModern.Blazor.DirectCommunication.csproj" />
	  </ItemGroup>

</Project>
