<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EverModern.WheelProtection.DataWorks" Version="0.0.12" />
		<PackageReference Include="EverModern.Threading" Version="0.0.42" />
		<PackageReference Include="EverModern.WheelProtection.Extensions" Version="0.0.26" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
	</ItemGroup>
	
</Project>
